[build]
command = "cd client && npm install && npm run build"
functions = "netlify/functions"
publish = "client/build"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
timeout = 25